FROM python:slim
LABEL maintainer="Ashley Walker ashley.walker@infarm.io"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \ 
    apt-get install -y --no-install-recommends git

WORKDIR /server
COPY ./requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

COPY . .

# HEALTHCHECK CMD curl --fail http://localhost:8080/ || exit 1

ENTRYPOINT ["/bin/bash", "-c"]

CMD ["python gRPC_server.py"]